run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - dupl
    - errname
    - errorlint
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - revive
    - stylecheck
    - unconvert
    - unparam
    - whitespace

linters-settings:
  funlen:
    lines: 100
    statements: 50
  
  gocognit:
    min-complexity: 20
  
  gocyclo:
    min-complexity: 15
  
  lll:
    line-length: 120
  
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocognit
        - gocyclo
