name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21', '1.22', '1.23' ]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -race -covermode=atomic -coverprofile=coverage.out ./...

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Build for multiple platforms
      run: |
        # Build for Linux
        GOOS=linux GOARCH=amd64 go build -o temp-deleter-linux-amd64 ./cmd/temp-deleter
        
        # Build for Windows
        GOOS=windows GOARCH=amd64 go build -o temp-deleter-windows-amd64.exe ./cmd/temp-deleter
        
        # Build for macOS
        GOOS=darwin GOARCH=amd64 go build -o temp-deleter-darwin-amd64 ./cmd/temp-deleter
        GOOS=darwin GOARCH=arm64 go build -o temp-deleter-darwin-arm64 ./cmd/temp-deleter

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: |
          temp-deleter-*
        retention-days: 7
